[workspace]

members = [
    "etptypes-rs",
    "etpproto-rs",
    "etpclient-rs",
]

[workspace.dependencies]

serde = { version = "1.0.151", features = ["derive"] }
serde_json = "1.0.105"
uuid = { version = "1.4.1", features = ["v4", "serde"] }
